name: CD Workflow

on:
  pull_request:
    branches:
      - main

jobs:
 deploy-to-development:
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'clean-code-arch'
    environment: development # Specify the environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Install lftp
      run: sudo apt-get install -y lftp

    - name: Deploy via FTP
      env:
        FTP_SERVER: ${{ secrets.DEVELOPMENT_IP }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        lftp -c "set ftp:ssl-allow no; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER; mirror -R --parallel=100 ./ wp-content/plugins/quizzes"

#    - name: Connect to server using SSH
#      uses: appleboy/ssh-action@v1.0.3  # Use the SSH action
#      with:
#          host: ${{ secrets.DEVELOPMENT_IP }}
#          username: ${{ secrets.DEVELOPMENT_USERNAME }}
#          key: ${{ secrets.DEVELOPMENT_PRIVATE_KEY }}  # Optional, if not using a key file
#          passphrase: ${{ secrets.DEVELOPMENT_PASSPHRASE }}
#          script: ls -l ~/public_html/dev.healoneself/wp-content/plugins/quizzes
 