name: CD Workflow

on:
  pull_request:
    branches:
      - main

jobs:
 deploy-to-development:
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'clean-code-arch'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install rsync
      run: sudo apt-get install -y rsync

    - name: Copy files to development server
      env:
        DEVELOPMENT_IP: ${{ secrets.DEVELOPMENT_IP }}
        DEVELOPMENT_USERNAME: ${{ secrets.DEVELOPMENT_USERNAME }}
        DEVELOPMENT_PASSWORD: ${{ secrets.DEVELOPMENT_PASSWORD }}
      run: |
        echo "${DEVELOPMENT_PASSWORD}" > /tmp/development_password
        chmod 600 /tmp/DEVELOPMENT_PASSWORD
        rsync -avz --delete -e "ssh -i /tmp/DEVELOPMENT_PASSWORD -o StrictHostKeyChecking=no" . ${DEVELOPMENT_USERNAME}@${DEVELOPMENT_IP}:/public_html/dev.healoneself/wp-content/plugins/quizzes
        rm /tmp/DEVELOPMENT_PASSWORD