name: CD Workflow

on:
  pull_request:
    branches:
      - main

jobs:
 deploy-to-development:
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'clean-code-arch'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install rsync
      run: sudo apt-get install -y rsync

    - name: SSH into server and list files
      env:
        DEVELOPMENT_IP: ${{ env.DEVELOPMENT_IP }}
        DEVELOPMENT_USERNAME: ${{ secrets.DEVELOPMENT_USERNAME }}
        DEVELOPMENT_PASSWORD: ${{ secrets.DEVELOPMENT_PASSWORD }}
      run: |
        echo "${{ secrets.DEVELOPMENT_PASSWORD }}" > /tmp/development_password
        chmod 600 /tmp/development_password
        sshpass -f /tmp/development_password ssh -o StrictHostKeyChecking=no ${DEVELOPMENT_USERNAME}@${DEVELOPMENT_IP} "ls -l /public_html/dev.healoneself/wp-content/plugins/quizzes"